version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend
    networks:
      - mynetwork

  app:
    build: ./backend
    ports:
      - 8000:8000
    container_name: app
    networks:
      - mynetwork

  user-log:
    build: ./backend/user_log_microservice
    ports:
      - 8001:8001
    container_name: user-log
    networks:
      - mynetwork

  password:
    build: ./backend/password_manager_microservice
    ports:
      - 8002:8002
    container_name: password
    networks:
      - mynetwork

  session:
    build: ./backend/session_microservice
    ports:
      - 8003:8003
    container_name: session
    networks:
      - mynetwork

  transactions:
    build: ./backend/transactions_microservice
    ports:
      - 8005:8005
    container_name: transactions
    networks:
      - mynetwork

  user-data:
    build: ./backend/user_data_microservice
    ports:
      - 8004:8004
    container_name: user-data
    networks:
      - mynetwork

networks:
  mynetwork:
    name: insideNetwork
    driver: bridge
